export type Country = {
  name: string
  code: string
  dial: string
  flag: string
  digits: number
}

// Generated from libphonenumber. Nigeria first (app default), then alphabetical.
// `digits` = national number length including the leading trunk 0,
// so the phone input accepts `digits - 1` typed characters.
export const COUNTRIES: Country[] = [
  { name: 'Nigeria', code: 'NG', dial: '+234', flag: '🇳🇬', digits: 11 },
  { name: 'Afghanistan', code: 'AF', dial: '+93', flag: '🇦🇫', digits: 10 },
  { name: 'Albania', code: 'AL', dial: '+355', flag: '🇦🇱', digits: 10 },
  { name: 'Algeria', code: 'DZ', dial: '+213', flag: '🇩🇿', digits: 10 },
  { name: 'American Samoa', code: 'AS', dial: '+1', flag: '🇦🇸', digits: 11 },
  { name: 'Andorra', code: 'AD', dial: '+376', flag: '🇦🇩', digits: 7 },
  { name: 'Angola', code: 'AO', dial: '+244', flag: '🇦🇴', digits: 10 },
  { name: 'Anguilla', code: 'AI', dial: '+1', flag: '🇦🇮', digits: 11 },
  { name: 'Antigua and Barbuda', code: 'AG', dial: '+1', flag: '🇦🇬', digits: 11 },
  { name: 'Argentina', code: 'AR', dial: '+54', flag: '🇦🇷', digits: 12 },
  { name: 'Armenia', code: 'AM', dial: '+374', flag: '🇦🇲', digits: 9 },
  { name: 'Aruba', code: 'AW', dial: '+297', flag: '🇦🇼', digits: 8 },
  { name: 'Australia', code: 'AU', dial: '+61', flag: '🇦🇺', digits: 10 },
  { name: 'Austria', code: 'AT', dial: '+43', flag: '🇦🇹', digits: 10 },
  { name: 'Azerbaijan', code: 'AZ', dial: '+994', flag: '🇦🇿', digits: 10 },
  { name: 'Bahamas', code: 'BS', dial: '+1', flag: '🇧🇸', digits: 11 },
  { name: 'Bahrain', code: 'BH', dial: '+973', flag: '🇧🇭', digits: 9 },
  { name: 'Bangladesh', code: 'BD', dial: '+880', flag: '🇧🇩', digits: 11 },
  { name: 'Barbados', code: 'BB', dial: '+1', flag: '🇧🇧', digits: 11 },
  { name: 'Belarus', code: 'BY', dial: '+375', flag: '🇧🇾', digits: 10 },
  { name: 'Belgium', code: 'BE', dial: '+32', flag: '🇧🇪', digits: 10 },
  { name: 'Belize', code: 'BZ', dial: '+501', flag: '🇧🇿', digits: 8 },
  { name: 'Benin', code: 'BJ', dial: '+229', flag: '🇧🇯', digits: 10 },
  { name: 'Bermuda', code: 'BM', dial: '+1', flag: '🇧🇲', digits: 11 },
  { name: 'Bhutan', code: 'BT', dial: '+975', flag: '🇧🇹', digits: 9 },
  { name: 'Bolivia', code: 'BO', dial: '+591', flag: '🇧🇴', digits: 9 },
  { name: 'Bosnia and Herzegovina', code: 'BA', dial: '+387', flag: '🇧🇦', digits: 9 },
  { name: 'Botswana', code: 'BW', dial: '+267', flag: '🇧🇼', digits: 9 },
  { name: 'Brazil', code: 'BR', dial: '+55', flag: '🇧🇷', digits: 12 },
  { name: 'British Indian Ocean Territory', code: 'IO', dial: '+246', flag: '🇮🇴', digits: 8 },
  { name: 'British Virgin Islands', code: 'VG', dial: '+1', flag: '🇻🇬', digits: 11 },
  { name: 'Brunei', code: 'BN', dial: '+673', flag: '🇧🇳', digits: 8 },
  { name: 'Bulgaria', code: 'BG', dial: '+359', flag: '🇧🇬', digits: 9 },
  { name: 'Burkina Faso', code: 'BF', dial: '+226', flag: '🇧🇫', digits: 9 },
  { name: 'Burundi', code: 'BI', dial: '+257', flag: '🇧🇮', digits: 9 },
  { name: 'Cambodia', code: 'KH', dial: '+855', flag: '🇰🇭', digits: 9 },
  { name: 'Cameroon', code: 'CM', dial: '+237', flag: '🇨🇲', digits: 10 },
  { name: 'Canada', code: 'CA', dial: '+1', flag: '🇨🇦', digits: 11 },
  { name: 'Cape Verde', code: 'CV', dial: '+238', flag: '🇨🇻', digits: 8 },
  { name: 'Caribbean Netherlands', code: 'BQ', dial: '+599', flag: '🇧🇶', digits: 8 },
  { name: 'Cayman Islands', code: 'KY', dial: '+1', flag: '🇰🇾', digits: 11 },
  { name: 'Central African Republic', code: 'CF', dial: '+236', flag: '🇨🇫', digits: 9 },
  { name: 'Chad', code: 'TD', dial: '+235', flag: '🇹🇩', digits: 9 },
  { name: 'Chile', code: 'CL', dial: '+56', flag: '🇨🇱', digits: 10 },
  { name: 'China', code: 'CN', dial: '+86', flag: '🇨🇳', digits: 12 },
  { name: 'Christmas Island', code: 'CX', dial: '+61', flag: '🇨🇽', digits: 10 },
  { name: 'Cocos (Keeling) Islands', code: 'CC', dial: '+61', flag: '🇨🇨', digits: 10 },
  { name: 'Colombia', code: 'CO', dial: '+57', flag: '🇨🇴', digits: 11 },
  { name: 'Comoros', code: 'KM', dial: '+269', flag: '🇰🇲', digits: 8 },
  { name: 'Cook Islands', code: 'CK', dial: '+682', flag: '🇨🇰', digits: 6 },
  { name: 'Costa Rica', code: 'CR', dial: '+506', flag: '🇨🇷', digits: 9 },
  { name: 'Cote d\'Ivoire', code: 'CI', dial: '+225', flag: '🇨🇮', digits: 10 },
  { name: 'Croatia', code: 'HR', dial: '+385', flag: '🇭🇷', digits: 10 },
  { name: 'Cuba', code: 'CU', dial: '+53', flag: '🇨🇺', digits: 9 },
  { name: 'Curaçao', code: 'CW', dial: '+599', flag: '🇨🇼', digits: 9 },
  { name: 'Cyprus', code: 'CY', dial: '+357', flag: '🇨🇾', digits: 9 },
  { name: 'Czechia', code: 'CZ', dial: '+420', flag: '🇨🇿', digits: 10 },
  { name: 'DR Congo', code: 'CD', dial: '+243', flag: '🇨🇩', digits: 10 },
  { name: 'Denmark', code: 'DK', dial: '+45', flag: '🇩🇰', digits: 9 },
  { name: 'Djibouti', code: 'DJ', dial: '+253', flag: '🇩🇯', digits: 9 },
  { name: 'Dominica', code: 'DM', dial: '+1', flag: '🇩🇲', digits: 11 },
  { name: 'Dominican Republic', code: 'DO', dial: '+1', flag: '🇩🇴', digits: 11 },
  { name: 'Ecuador', code: 'EC', dial: '+593', flag: '🇪🇨', digits: 10 },
  { name: 'Egypt', code: 'EG', dial: '+20', flag: '🇪🇬', digits: 11 },
  { name: 'El Salvador', code: 'SV', dial: '+503', flag: '🇸🇻', digits: 9 },
  { name: 'Equatorial Guinea', code: 'GQ', dial: '+240', flag: '🇬🇶', digits: 10 },
  { name: 'Eritrea', code: 'ER', dial: '+291', flag: '🇪🇷', digits: 8 },
  { name: 'Estonia', code: 'EE', dial: '+372', flag: '🇪🇪', digits: 9 },
  { name: 'Eswatini', code: 'SZ', dial: '+268', flag: '🇸🇿', digits: 9 },
  { name: 'Ethiopia', code: 'ET', dial: '+251', flag: '🇪🇹', digits: 10 },
  { name: 'Falkland Islands', code: 'FK', dial: '+500', flag: '🇫🇰', digits: 6 },
  { name: 'Faroe Islands', code: 'FO', dial: '+298', flag: '🇫🇴', digits: 7 },
  { name: 'Fiji', code: 'FJ', dial: '+679', flag: '🇫🇯', digits: 8 },
  { name: 'Finland', code: 'FI', dial: '+358', flag: '🇫🇮', digits: 10 },
  { name: 'France', code: 'FR', dial: '+33', flag: '🇫🇷', digits: 10 },
  { name: 'French Guiana', code: 'GF', dial: '+594', flag: '🇬🇫', digits: 10 },
  { name: 'French Polynesia', code: 'PF', dial: '+689', flag: '🇵🇫', digits: 9 },
  { name: 'Gabon', code: 'GA', dial: '+241', flag: '🇬🇦', digits: 8 },
  { name: 'Gambia', code: 'GM', dial: '+220', flag: '🇬🇲', digits: 8 },
  { name: 'Georgia', code: 'GE', dial: '+995', flag: '🇬🇪', digits: 10 },
  { name: 'Germany', code: 'DE', dial: '+49', flag: '🇩🇪', digits: 12 },
  { name: 'Ghana', code: 'GH', dial: '+233', flag: '🇬🇭', digits: 10 },
  { name: 'Gibraltar', code: 'GI', dial: '+350', flag: '🇬🇮', digits: 9 },
  { name: 'Greece', code: 'GR', dial: '+30', flag: '🇬🇷', digits: 11 },
  { name: 'Greenland', code: 'GL', dial: '+299', flag: '🇬🇱', digits: 7 },
  { name: 'Grenada', code: 'GD', dial: '+1', flag: '🇬🇩', digits: 11 },
  { name: 'Guadeloupe', code: 'GP', dial: '+590', flag: '🇬🇵', digits: 10 },
  { name: 'Guam', code: 'GU', dial: '+1', flag: '🇬🇺', digits: 11 },
  { name: 'Guatemala', code: 'GT', dial: '+502', flag: '🇬🇹', digits: 9 },
  { name: 'Guernsey', code: 'GG', dial: '+44', flag: '🇬🇬', digits: 11 },
  { name: 'Guinea', code: 'GN', dial: '+224', flag: '🇬🇳', digits: 10 },
  { name: 'Guinea-Bissau', code: 'GW', dial: '+245', flag: '🇬🇼', digits: 10 },
  { name: 'Guyana', code: 'GY', dial: '+592', flag: '🇬🇾', digits: 8 },
  { name: 'Haiti', code: 'HT', dial: '+509', flag: '🇭🇹', digits: 9 },
  { name: 'Honduras', code: 'HN', dial: '+504', flag: '🇭🇳', digits: 9 },
  { name: 'Hong Kong', code: 'HK', dial: '+852', flag: '🇭🇰', digits: 9 },
  { name: 'Hungary', code: 'HU', dial: '+36', flag: '🇭🇺', digits: 10 },
  { name: 'Iceland', code: 'IS', dial: '+354', flag: '🇮🇸', digits: 8 },
  { name: 'India', code: 'IN', dial: '+91', flag: '🇮🇳', digits: 11 },
  { name: 'Indonesia', code: 'ID', dial: '+62', flag: '🇮🇩', digits: 10 },
  { name: 'Iran', code: 'IR', dial: '+98', flag: '🇮🇷', digits: 11 },
  { name: 'Iraq', code: 'IQ', dial: '+964', flag: '🇮🇶', digits: 11 },
  { name: 'Ireland', code: 'IE', dial: '+353', flag: '🇮🇪', digits: 10 },
  { name: 'Isle of Man', code: 'IM', dial: '+44', flag: '🇮🇲', digits: 11 },
  { name: 'Israel', code: 'IL', dial: '+972', flag: '🇮🇱', digits: 10 },
  { name: 'Italy', code: 'IT', dial: '+39', flag: '🇮🇹', digits: 11 },
  { name: 'Jamaica', code: 'JM', dial: '+1', flag: '🇯🇲', digits: 11 },
  { name: 'Japan', code: 'JP', dial: '+81', flag: '🇯🇵', digits: 11 },
  { name: 'Jersey', code: 'JE', dial: '+44', flag: '🇯🇪', digits: 11 },
  { name: 'Jordan', code: 'JO', dial: '+962', flag: '🇯🇴', digits: 10 },
  { name: 'Kazakhstan', code: 'KZ', dial: '+7', flag: '🇰🇿', digits: 11 },
  { name: 'Kenya', code: 'KE', dial: '+254', flag: '🇰🇪', digits: 10 },
  { name: 'Kiribati', code: 'KI', dial: '+686', flag: '🇰🇮', digits: 9 },
  { name: 'Kuwait', code: 'KW', dial: '+965', flag: '🇰🇼', digits: 9 },
  { name: 'Kyrgyzstan', code: 'KG', dial: '+996', flag: '🇰🇬', digits: 10 },
  { name: 'Laos', code: 'LA', dial: '+856', flag: '🇱🇦', digits: 11 },
  { name: 'Latvia', code: 'LV', dial: '+371', flag: '🇱🇻', digits: 9 },
  { name: 'Lebanon', code: 'LB', dial: '+961', flag: '🇱🇧', digits: 9 },
  { name: 'Lesotho', code: 'LS', dial: '+266', flag: '🇱🇸', digits: 9 },
  { name: 'Liberia', code: 'LR', dial: '+231', flag: '🇱🇷', digits: 10 },
  { name: 'Libya', code: 'LY', dial: '+218', flag: '🇱🇾', digits: 10 },
  { name: 'Liechtenstein', code: 'LI', dial: '+423', flag: '🇱🇮', digits: 10 },
  { name: 'Lithuania', code: 'LT', dial: '+370', flag: '🇱🇹', digits: 9 },
  { name: 'Luxembourg', code: 'LU', dial: '+352', flag: '🇱🇺', digits: 10 },
  { name: 'Macau', code: 'MO', dial: '+853', flag: '🇲🇴', digits: 9 },
  { name: 'Madagascar', code: 'MG', dial: '+261', flag: '🇲🇬', digits: 10 },
  { name: 'Malawi', code: 'MW', dial: '+265', flag: '🇲🇼', digits: 10 },
  { name: 'Malaysia', code: 'MY', dial: '+60', flag: '🇲🇾', digits: 10 },
  { name: 'Maldives', code: 'MV', dial: '+960', flag: '🇲🇻', digits: 8 },
  { name: 'Mali', code: 'ML', dial: '+223', flag: '🇲🇱', digits: 9 },
  { name: 'Malta', code: 'MT', dial: '+356', flag: '🇲🇹', digits: 9 },
  { name: 'Marshall Islands', code: 'MH', dial: '+692', flag: '🇲🇭', digits: 8 },
  { name: 'Martinique', code: 'MQ', dial: '+596', flag: '🇲🇶', digits: 10 },
  { name: 'Mauritania', code: 'MR', dial: '+222', flag: '🇲🇷', digits: 9 },
  { name: 'Mauritius', code: 'MU', dial: '+230', flag: '🇲🇺', digits: 9 },
  { name: 'Mayotte', code: 'YT', dial: '+262', flag: '🇾🇹', digits: 10 },
  { name: 'Mexico', code: 'MX', dial: '+52', flag: '🇲🇽', digits: 11 },
  { name: 'Micronesia', code: 'FM', dial: '+691', flag: '🇫🇲', digits: 8 },
  { name: 'Moldova', code: 'MD', dial: '+373', flag: '🇲🇩', digits: 9 },
  { name: 'Monaco', code: 'MC', dial: '+377', flag: '🇲🇨', digits: 10 },
  { name: 'Mongolia', code: 'MN', dial: '+976', flag: '🇲🇳', digits: 9 },
  { name: 'Montenegro', code: 'ME', dial: '+382', flag: '🇲🇪', digits: 9 },
  { name: 'Montserrat', code: 'MS', dial: '+1', flag: '🇲🇸', digits: 11 },
  { name: 'Morocco', code: 'MA', dial: '+212', flag: '🇲🇦', digits: 10 },
  { name: 'Mozambique', code: 'MZ', dial: '+258', flag: '🇲🇿', digits: 10 },
  { name: 'Myanmar', code: 'MM', dial: '+95', flag: '🇲🇲', digits: 9 },
  { name: 'Namibia', code: 'NA', dial: '+264', flag: '🇳🇦', digits: 10 },
  { name: 'Nauru', code: 'NR', dial: '+674', flag: '🇳🇷', digits: 8 },
  { name: 'Nepal', code: 'NP', dial: '+977', flag: '🇳🇵', digits: 11 },
  { name: 'Netherlands', code: 'NL', dial: '+31', flag: '🇳🇱', digits: 10 },
  { name: 'New Caledonia', code: 'NC', dial: '+687', flag: '🇳🇨', digits: 7 },
  { name: 'New Zealand', code: 'NZ', dial: '+64', flag: '🇳🇿', digits: 10 },
  { name: 'Nicaragua', code: 'NI', dial: '+505', flag: '🇳🇮', digits: 9 },
  { name: 'Niger', code: 'NE', dial: '+227', flag: '🇳🇪', digits: 9 },
  { name: 'Niue', code: 'NU', dial: '+683', flag: '🇳🇺', digits: 8 },
  { name: 'Norfolk Island', code: 'NF', dial: '+672', flag: '🇳🇫', digits: 7 },
  { name: 'North Korea', code: 'KP', dial: '+850', flag: '🇰🇵', digits: 11 },
  { name: 'North Macedonia', code: 'MK', dial: '+389', flag: '🇲🇰', digits: 9 },
  { name: 'Northern Mariana Islands', code: 'MP', dial: '+1', flag: '🇲🇵', digits: 11 },
  { name: 'Norway', code: 'NO', dial: '+47', flag: '🇳🇴', digits: 9 },
  { name: 'Oman', code: 'OM', dial: '+968', flag: '🇴🇲', digits: 9 },
  { name: 'Pakistan', code: 'PK', dial: '+92', flag: '🇵🇰', digits: 11 },
  { name: 'Palau', code: 'PW', dial: '+680', flag: '🇵🇼', digits: 8 },
  { name: 'Palestine', code: 'PS', dial: '+970', flag: '🇵🇸', digits: 10 },
  { name: 'Panama', code: 'PA', dial: '+507', flag: '🇵🇦', digits: 9 },
  { name: 'Papua New Guinea', code: 'PG', dial: '+675', flag: '🇵🇬', digits: 9 },
  { name: 'Paraguay', code: 'PY', dial: '+595', flag: '🇵🇾', digits: 10 },
  { name: 'Peru', code: 'PE', dial: '+51', flag: '🇵🇪', digits: 10 },
  { name: 'Philippines', code: 'PH', dial: '+63', flag: '🇵🇭', digits: 11 },
  { name: 'Poland', code: 'PL', dial: '+48', flag: '🇵🇱', digits: 10 },
  { name: 'Portugal', code: 'PT', dial: '+351', flag: '🇵🇹', digits: 10 },
  { name: 'Puerto Rico', code: 'PR', dial: '+1', flag: '🇵🇷', digits: 11 },
  { name: 'Qatar', code: 'QA', dial: '+974', flag: '🇶🇦', digits: 9 },
  { name: 'Republic of the Congo', code: 'CG', dial: '+242', flag: '🇨🇬', digits: 9 },
  { name: 'Romania', code: 'RO', dial: '+40', flag: '🇷🇴', digits: 10 },
  { name: 'Russia', code: 'RU', dial: '+7', flag: '🇷🇺', digits: 11 },
  { name: 'Rwanda', code: 'RW', dial: '+250', flag: '🇷🇼', digits: 10 },
  { name: 'Réunion', code: 'RE', dial: '+262', flag: '🇷🇪', digits: 10 },
  { name: 'Saint Barthélemy', code: 'BL', dial: '+590', flag: '🇧🇱', digits: 10 },
  { name: 'Saint Helena', code: 'SH', dial: '+290', flag: '🇸🇭', digits: 6 },
  { name: 'Saint Kitts and Nevis', code: 'KN', dial: '+1', flag: '🇰🇳', digits: 11 },
  { name: 'Saint Lucia', code: 'LC', dial: '+1', flag: '🇱🇨', digits: 11 },
  { name: 'Saint Martin (French part)', code: 'MF', dial: '+590', flag: '🇲🇫', digits: 10 },
  { name: 'Saint Pierre and Miquelon', code: 'PM', dial: '+508', flag: '🇵🇲', digits: 7 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', dial: '+1', flag: '🇻🇨', digits: 11 },
  { name: 'Samoa', code: 'WS', dial: '+685', flag: '🇼🇸', digits: 8 },
  { name: 'San Marino', code: 'SM', dial: '+378', flag: '🇸🇲', digits: 9 },
  { name: 'Sao Tome and Principe', code: 'ST', dial: '+239', flag: '🇸🇹', digits: 8 },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966', flag: '🇸🇦', digits: 10 },
  { name: 'Senegal', code: 'SN', dial: '+221', flag: '🇸🇳', digits: 10 },
  { name: 'Serbia', code: 'RS', dial: '+381', flag: '🇷🇸', digits: 10 },
  { name: 'Seychelles', code: 'SC', dial: '+248', flag: '🇸🇨', digits: 8 },
  { name: 'Sierra Leone', code: 'SL', dial: '+232', flag: '🇸🇱', digits: 9 },
  { name: 'Singapore', code: 'SG', dial: '+65', flag: '🇸🇬', digits: 9 },
  { name: 'Sint Maarten', code: 'SX', dial: '+1', flag: '🇸🇽', digits: 11 },
  { name: 'Slovakia', code: 'SK', dial: '+421', flag: '🇸🇰', digits: 10 },
  { name: 'Slovenia', code: 'SI', dial: '+386', flag: '🇸🇮', digits: 9 },
  { name: 'Solomon Islands', code: 'SB', dial: '+677', flag: '🇸🇧', digits: 8 },
  { name: 'Somalia', code: 'SO', dial: '+252', flag: '🇸🇴', digits: 9 },
  { name: 'South Africa', code: 'ZA', dial: '+27', flag: '🇿🇦', digits: 10 },
  { name: 'South Korea', code: 'KR', dial: '+82', flag: '🇰🇷', digits: 11 },
  { name: 'South Sudan', code: 'SS', dial: '+211', flag: '🇸🇸', digits: 10 },
  { name: 'Spain', code: 'ES', dial: '+34', flag: '🇪🇸', digits: 10 },
  { name: 'Sri Lanka', code: 'LK', dial: '+94', flag: '🇱🇰', digits: 10 },
  { name: 'Sudan', code: 'SD', dial: '+249', flag: '🇸🇩', digits: 10 },
  { name: 'Suriname', code: 'SR', dial: '+597', flag: '🇸🇷', digits: 8 },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', dial: '+47', flag: '🇸🇯', digits: 9 },
  { name: 'Sweden', code: 'SE', dial: '+46', flag: '🇸🇪', digits: 10 },
  { name: 'Switzerland', code: 'CH', dial: '+41', flag: '🇨🇭', digits: 10 },
  { name: 'Syria', code: 'SY', dial: '+963', flag: '🇸🇾', digits: 10 },
  { name: 'Taiwan', code: 'TW', dial: '+886', flag: '🇹🇼', digits: 10 },
  { name: 'Tajikistan', code: 'TJ', dial: '+992', flag: '🇹🇯', digits: 10 },
  { name: 'Tanzania', code: 'TZ', dial: '+255', flag: '🇹🇿', digits: 10 },
  { name: 'Thailand', code: 'TH', dial: '+66', flag: '🇹🇭', digits: 10 },
  { name: 'Timor-Leste', code: 'TL', dial: '+670', flag: '🇹🇱', digits: 9 },
  { name: 'Togo', code: 'TG', dial: '+228', flag: '🇹🇬', digits: 9 },
  { name: 'Tokelau', code: 'TK', dial: '+690', flag: '🇹🇰', digits: 5 },
  { name: 'Tonga', code: 'TO', dial: '+676', flag: '🇹🇴', digits: 8 },
  { name: 'Trinidad and Tobago', code: 'TT', dial: '+1', flag: '🇹🇹', digits: 11 },
  { name: 'Tunisia', code: 'TN', dial: '+216', flag: '🇹🇳', digits: 9 },
  { name: 'Turkmenistan', code: 'TM', dial: '+993', flag: '🇹🇲', digits: 9 },
  { name: 'Turks and Caicos Islands', code: 'TC', dial: '+1', flag: '🇹🇨', digits: 11 },
  { name: 'Tuvalu', code: 'TV', dial: '+688', flag: '🇹🇻', digits: 7 },
  { name: 'Türkiye', code: 'TR', dial: '+90', flag: '🇹🇷', digits: 11 },
  { name: 'US Virgin Islands', code: 'VI', dial: '+1', flag: '🇻🇮', digits: 11 },
  { name: 'Uganda', code: 'UG', dial: '+256', flag: '🇺🇬', digits: 10 },
  { name: 'Ukraine', code: 'UA', dial: '+380', flag: '🇺🇦', digits: 10 },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971', flag: '🇦🇪', digits: 10 },
  { name: 'United Kingdom', code: 'GB', dial: '+44', flag: '🇬🇧', digits: 11 },
  { name: 'United States', code: 'US', dial: '+1', flag: '🇺🇸', digits: 11 },
  { name: 'Uruguay', code: 'UY', dial: '+598', flag: '🇺🇾', digits: 9 },
  { name: 'Uzbekistan', code: 'UZ', dial: '+998', flag: '🇺🇿', digits: 10 },
  { name: 'Vanuatu', code: 'VU', dial: '+678', flag: '🇻🇺', digits: 8 },
  { name: 'Vatican City', code: 'VA', dial: '+39', flag: '🇻🇦', digits: 11 },
  { name: 'Venezuela', code: 'VE', dial: '+58', flag: '🇻🇪', digits: 11 },
  { name: 'Vietnam', code: 'VN', dial: '+84', flag: '🇻🇳', digits: 10 },
  { name: 'Wallis and Futuna', code: 'WF', dial: '+681', flag: '🇼🇫', digits: 7 },
  { name: 'Western Sahara', code: 'EH', dial: '+212', flag: '🇪🇭', digits: 10 },
  { name: 'Yemen', code: 'YE', dial: '+967', flag: '🇾🇪', digits: 10 },
  { name: 'Zambia', code: 'ZM', dial: '+260', flag: '🇿🇲', digits: 10 },
  { name: 'Zimbabwe', code: 'ZW', dial: '+263', flag: '🇿🇼', digits: 10 },
  { name: 'Åland Islands', code: 'AX', dial: '+358', flag: '🇦🇽', digits: 10 },
]
